// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.techhouse.shirts.data.entities;

import org.joda.time.DateTime;

privileged aspect Configuration_Roo_JavaBean {
    
    public DateTime Configuration.getDeadline() {
        return this.deadline;
    }
    
    public void Configuration.setDeadline(DateTime deadline) {
        this.deadline = deadline;
    }
    
}
